name: Rust checks

on:
  push:
    branches: [main, tui]
  pull_request:
    branches: [main, tui]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run Clippy
        run: cargo clippy --workspace --all-targets
      - name: Run tests
        run: cargo test --workspace --no-fail-fast
